language: python
python:
  - '3.7' 
dist: bionic

before_install:
  - git clone --depth 1 --branch v2.1.0-1 https://github.com/ait-aecid/aminer-ansible.git roles/aminer
  - sed -e "s+{{SOURCEDIR}}+$PWD+g" .playbook.yml > playbook.yml

install:
  - sudo apt-get update -y
  - sudo apt-get install -y ansible
  - sudo ansible-playbook playbook.yml
